name = "telegram2"
main = "worker.js"
compatibility_date = "2026-02-15"

[triggers]
crons = ["0 * * * *"]

[[kv_namespaces]]
binding = "PREFS_KV"
id = "bec163350c35472ba3233430b1b4d6ba"

[vars]
BASE_MONDAY = "2026-02-09"
BASE_WEEK_TYPE = "numerator"
BOT_TOKEN = "8584284374:AAFwh8zU8yzwKjbHgBK8oyJBM9yYyXcVq0M"
FIREBASE_API_KEY = "AIzaSyBH8JKNOBWTjxSIINVI8LiwK8u9sPyVTo"
SITE_URL = "https://xmice7.github.io/sitetg/"
TZ_OFFSET_MIN = "120"
VERCEL_URL = "https://sitetg-kappa.vercel.app"
WORKER_URL = "https://telegram2.korglosa.workers.dev"
SUPPORT_GROUP_ID = "-5380258098"
ADMIN_USER_ID = "918235475"


